export default {
  ACCOUNT_LIST: '账户列表',
  BALANCE: '账户明细',
  COPIED_TO_CLIPBOARD: '已复制!',
  COPY_ADDRESS: '复制地址',
  COPY_PRIVATE_KEY: '复制私钥',
  CREATE_NEW_ACCOUNT: '创建新账户',
  EXPORT_PRIVATE_KEY: '导出私钥',
  REMOVE_ACCOUNT: '删除账户',
  CONFIRM_REMOVE_ACCOUNT: '确定删除账户',
  FAIL_FIND_ACCOUNT: '无找到指定账户',
  FAILED_COPIED_TO_CLIPBOARD: '复制失败!',
  GUARD_PRIVATE_KEY_SAFELY: '请注意妥善保管私钥，勿泄露给其他人',
  MAKE_DEFAULT_ACCOUNT: '设置为默认账户',
  NO_ACCOUNT_AVAILABLE: 'No account available',
  PRIVATE_KEY_IMPORTED_ALREADY: '无法创建此账户，该私钥已存在。',
  PRIVATE_KEY: '私钥',
  SHOW_ACCOUNT_BALANCE: '显示账户明细',
  SHOW_ADDRESS_AS_QR: '地址QR码',
  ACCOUNT_CREATE_SUCCESSFUL: '成功创建账户',
  ACCOUNT_IMPORT_SUCCESSFUL: '成功导入账户',
  NETWORK: 'Network',
  NETWORK_NAVIGATION_SECONDARY_TEXT: 'View and create network',
  ABOUT: 'About',
  ABOUT_NAVIGATION_SECONDARY_TEXT: 'Learn more about everiSigner',
  SET_NETWORK_AS_DEFAULT: '设置为默认节点',
  REMOVE_NETWORK: '删除节点'
}
