export default {
  ABOUT_NAVIGATION_SECONDARY_TEXT: 'Learn more about everiSigner',
  ABOUT: 'About',
  ACCOUNT_CREATE_SUCCESSFUL: '成功创建账户',
  ACCOUNT_DETAIL: '账户',
  ACCOUNT_IMPORT_SUCCESSFUL: '成功导入账户',

  ACCOUNT_LIST_SECONDARY_TEXT: '账户列表',
  ACCOUNT_LIST: '账户列表',
  ACCOUNT_NAME: '账户名',
  ACCOUNT_SELECT: '选择账户',
  AUTHORIZE_BUTTON_TEXT: '授权',
  IMPORT_WALLET_FAILED: '导入账户失败',
  WALLET_BACKUP_FILE_LOADED: '钱包备份文件已导入',
  FILE_DETECTED: '检测到文件',
  SELECT_OR_DND: '选择备份文件或者将备份文件拖拽到此',
  IMPORT_WALLET_TITLE: '导入钱包',
  IMPORT_WALLET_DESCRIPTION:
    '使用钱包备份文件初始化钱包，此选项会导入备份文件中所有账户，助记词等。',
  IMPORT_WALLET_BTN: '导入钱包',
  IMPORT_WALLET_DESCRIPTION_0: '选择钱包备份文件',
  IMPORT_WALLET_DESCRIPTION_1: '提供备份文件的密码',
  IMPORT_WALLET_DESCRIPTION_2: 'everiSigner将验证备份文件并导入钱包',
  INPUT_WALLET_RECOEVER_PASSWORD: '输入备份文件解锁密码',
  BACKUP_WALLET_SECONDARY_TEXT: '将钱包加密保存到电脑',
  WALLET_NEED_SETUP: '钱包尚未完成设置。',
  WALLET_SETUP_BUTTON: '设置钱包',
  WALLET_CREATE: '设置新钱包',
  WALLET_CREATE_DESCRIPTION: '创建身份钱包，或通过助记词，私钥导入账户',
  BACKUP_INFO_TEXT_SAVE_TO_COMPUTER: '加密备份钱包至硬盘',
  BACKUP_INFO_TEXT_ADDITIONAL_PASSPHRASE:
    '钱包备份需要额外密码来保证安全。请妥善保存此密码用于恢复备份',
  BACKUP_WALLET_ADDITIONAL_PASSPHRASE_BTN_LABEL:
    '备份钱包需要额外密码密码以保证安全',
  BACKUP_INFO_TEXT_VERIFY_BACKUP: '验证备份',
  BACKUP_WALLET: '备份钱包',
  BACKUP_WALLET_BTN_TEXT: '备份钱包至本地',
  VERIFY_WALLET: '验证钱包',
  CANCEL_BUTTON_TEXT: '取消',
  CLICK_QR_TO_COPY: '点击二维码复制地址',
  CLOSE: '关闭窗口',
  CONFIRM_REMOVE_ACCOUNT: '确定删除账户',
  CONNECT_REQUEST: 'Connect Request',
  COPIED_TO_CLIPBOARD: '已复制!',
  COPY_ADDRESS: '复制地址',
  COPY_PRIVATE_KEY: '复制私钥',
  COPY_ADDRESS_SUCCESSFUL: '成功复制地址',
  COPY_PRIVATE_KEY_SUCCESSFUL: '成功复制私钥',
  CREATE_NETWORK: '创建节点',
  CREATE_NEW_ACCOUNT: '创建新账户',
  CREATE: '创建',
  FAIL_FIND_ACCOUNT: '无找到指定账户',
  FAILED_COPIED_TO_CLIPBOARD: '复制失败!',
  FUNGIBLE_BALANCE: '同质化通证',
  BALANCE_REST: '余额',
  GUARD_PRIVATE_KEY_SAFELY: '请注意妥善保管私钥，勿泄露给其他人',
  IMPORT_PRIVATE_KEY: '导入私钥',
  INPUT_MNEMONIC_WORDS: '输入助记词',
  MAKE_DEFAULT_ACCOUNT: '设置为默认账户',
  MNEMONIC_IMPORT: '助记词',
  MNEMONIC: '助记词',
  NETWORK_SELECT: '选择节点',
  NETWORK_LIST: '节点列表',
  NETWORK_NAME: '节点名称',
  NETWORK_NAVIGATION_SECONDARY_TEXT: 'View and create network',
  NETWORK_SUCCESSFULLY_CREATED: '成功添加节点',
  NETWORK_URL: '节点Url地址',
  NETWORK: '节点',
  NFTs_LIST: '非同质化通证',
  NFT_DETAIL: 'NFT detail',
  NO_ACCOUNT_AVAILABLE: 'No account available',
  PAYEE_CODE_SECONDARY_TEXT: '用于收款',
  PAYEE_CODE: '收款码',
  PRIVATE_KEY_IMPORT: '私钥',
  PRIVATE_KEY_IMPORTED_ALREADY: '无法创建此账户，该私钥已存在。',
  PRIVATE_KEY: '私钥',
  REMOVE_ACCOUNT_SECONDARY_TEXT: '从钱包中删除此账户',
  REMOVE_ACCOUNT: '删除账户',
  REMOVE_NETWORK: '删除节点',
  REQUEST_SIGNATURE: '签名请求',
  SET_NETWORK_AS_DEFAULT: '设置为默认节点',
  SHOW_ACCOUNT_BALANCE: '显示账户明细',
  SHOW_ADDRESS_AS_QR: '地址QR码',
  SHOW_PRIVATE_KEY_SECONDARY_TEXT: '再次输入密码显示私钥',
  SHOW_PRIVATE_KEY: '显示私钥',
  CURRENTLY_SIGNING: 'You are currently signing the following',
  SIGN: '签名',
  STEP_NEXT: '下一步',
  TO: '到',
  TRANSFERFT: '转账',
  TRANSFERFT_SECONDARY_TEXT: '转账到指定账户',
  UNSUPPORTED_ACTION_NAME: '尚未支持类型',
  SIGN_DATA: '签名数据',
  ACCOUNT_SIGN_SECONDARY_TEXT: '用于签名任意数据',
  ACCOUNT_SIGN_DESCRIPTION: '用当前的账户签名任意数据，签名将会出现再下方',
  DATA_TO_BE_SIGNED: '需要签名的数据',
  SIGNED_RESULT: '签名结果',
  UNLOCK: '解锁钱包',
  LOCK_WALLET: 'Lock Wallet',
  LOCK_WALLET_SECONDARY_TEXT: '将会锁定钱包，通过输入密码可重新开启',
  TYPE_PASSWORD_TO_UNLOCK: '输入密码解锁钱包',
  TOKEN_SELECT_SECONDARY_TEXT: '选择付款币种',
  ADDRESS_TO: '地址',
  ADDRESS_FORMAT_INVALID: '无效地址',
  TRANSFER_AMOUNT_INVALID: '无效转账金额',
  AMOUNT: '金额',
  MEMO: '备注 (Memo)',
  SETTINGS: '设置',
  BROWSE_SETTINGS: '浏览设置',
  TRANSFERRING: '转账进行中...',
  TRANSFER_FUNGIBLE_SUCCEED: '转账成功',
  TRANSFER_FAILED_ERROR_MSG: '转账失败',
}
